#ifndef DRIVEDEVICEAUDIT_GLOBAL_H
#define DRIVEDEVICEAUDIT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DRIVEDEVICEAUDIT_LIBRARY)
#  define DRIVEDEVICEAUDIT_EXPORT Q_DECL_EXPORT
#else
#  define DRIVEDEVICEAUDIT_EXPORT Q_DECL_IMPORT
#endif

#endif // DRIVEDEVICEAUDIT_GLOBAL_H
