#ifndef BASESYSTEMMONITORING_GLOBAL_H
#define BASESYSTEMMONITORING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BASESYSTEMMONITORING_LIBRARY)
#  define BASESYSTEMMONITORING_EXPORT Q_DECL_EXPORT
#else
#  define BASESYSTEMMONITORING_EXPORT Q_DECL_IMPORT
#endif

#endif // BASESYSTEMMONITORING_GLOBAL_H
