#ifndef CPUDEVICEAUDIT_GLOBAL_H
#define CPUDEVICEAUDIT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CPUDEVICEAUDIT_LIBRARY)
#  define CPUDEVICEAUDIT_EXPORT Q_DECL_EXPORT
#else
#  define CPUDEVICEAUDIT_EXPORT Q_DECL_IMPORT
#endif

#endif // CPUDEVICEAUDIT_GLOBAL_H
