#ifndef INITREMOTEDESKTOPCONNECTION_GLOBAL_H
#define INITREMOTEDESKTOPCONNECTION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(INITREMOTEDESKTOPCONNECTION_LIBRARY)
#  define INITREMOTEDESKTOPCONNECTION_EXPORT Q_DECL_EXPORT
#else
#  define INITREMOTEDESKTOPCONNECTION_EXPORT Q_DECL_IMPORT
#endif

#endif // INITREMOTEDESKTOPCONNECTION_GLOBAL_H
