#ifndef GPUDEVICEAUDIT_GLOBAL_H
#define GPUDEVICEAUDIT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GPUDEVICEAUDIT_LIBRARY)
#  define GPUDEVICEAUDIT_EXPORT Q_DECL_EXPORT
#else
#  define GPUDEVICEAUDIT_EXPORT Q_DECL_IMPORT
#endif

#endif // GPUDEVICEAUDIT_GLOBAL_H
