#ifndef LOCALNETWORKAUDIT_GLOBAL_H
#define LOCALNETWORKAUDIT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LOCALNETWORKAUDIT_LIBRARY)
#  define LOCALNETWORKAUDIT_EXPORT Q_DECL_EXPORT
#else
#  define LOCALNETWORKAUDIT_EXPORT Q_DECL_IMPORT
#endif

#endif // LOCALNETWORKAUDIT_GLOBAL_H
