#ifndef VMWARESYSTEMMONITORING_GLOBAL_H
#define VMWARESYSTEMMONITORING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VMWARESYSTEMMONITORING_LIBRARY)
#  define VMWARESYSTEMMONITORING_EXPORT Q_DECL_EXPORT
#else
#  define VMWARESYSTEMMONITORING_EXPORT Q_DECL_IMPORT
#endif

#endif // VMWARESYSTEMMONITORING_GLOBAL_H
