#ifndef PROCESSMONITORING_GLOBAL_H
#define PROCESSMONITORING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PROCESSMONITORING_LIBRARY)
#  define PROCESSMONITORING_EXPORT Q_DECL_EXPORT
#else
#  define PROCESSMONITORING_EXPORT Q_DECL_IMPORT
#endif

#endif // PROCESSMONITORING_GLOBAL_H
