#ifndef VMWARESYSTEMAUDIT_GLOBAL_H
#define VMWARESYSTEMAUDIT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VMWARESYSTEMAUDIT_LIBRARY)
#  define VMWARESYSTEMAUDIT_EXPORT Q_DECL_EXPORT
#else
#  define VMWARESYSTEMAUDIT_EXPORT Q_DECL_IMPORT
#endif

#endif // VMWARESYSTEMAUDIT_GLOBAL_H
