#ifndef VMHYPERVSYSTEMAUDIT_GLOBAL_H
#define VMHYPERVSYSTEMAUDIT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VMHYPERVSYSTEMAUDIT_LIBRARY)
#  define VMHYPERVSYSTEMAUDIT_EXPORT Q_DECL_EXPORT
#else
#  define VMHYPERVSYSTEMAUDIT_EXPORT Q_DECL_IMPORT
#endif

#endif // VMHYPERVSYSTEMAUDIT_GLOBAL_H
