#ifndef BASESYSTEMAUDIT_GLOBAL_H
#define BASESYSTEMAUDIT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BASESYSTEMAUDIT_LIBRARY)
#  define BASESYSTEMAUDIT_EXPORT Q_DECL_EXPORT
#else
#  define BASESYSTEMAUDIT_EXPORT Q_DECL_IMPORT
#endif

#endif // BASESYSTEMAUDIT_GLOBAL_H
