#ifndef DISPLAYDEVICEAUDIT_GLOBAL_H
#define DISPLAYDEVICEAUDIT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DISPLAYDEVICEAUDIT_LIBRARY)
#  define DISPLAYDEVICEAUDIT_EXPORT Q_DECL_EXPORT
#else
#  define DISPLAYDEVICEAUDIT_EXPORT Q_DECL_IMPORT
#endif

#endif // DISPLAYDEVICEAUDIT_GLOBAL_H
